### ISSUE TITLE
Doesn't seem to do anything...?

### ISSUE THREAD

**Issue by trevorturk** [adamsanderson/open_gem#1]
I did:

~ $ sudo gem install adamsanderson-open_gem
~ $ gem open rails
Chose #3, which is the most recent version...
Then nothing happened :(

echo $EDITOR returns: mate -w

Am I doing something wrong?

**Comment by tomafro** [comment]
Try installing the latest version (1.1.0), and setting $GEM_OPEN_EDITOR to 'mate' (without the -w)

**Comment by trevorturk** [comment]
It's working! Thanks - awesome job!
