### ISSUE TITLE
Fails silently if $EDITOR has arguments

### ISSUE THREAD

**Issue by grossbart** [adamsanderson/open_gem#2]
Just so you know: it wouldn't work at first (no reaction), because I had my $EDITOR set to `mate -w` which seems to silently mess things up. So I set $GEM_OPEN_EDITOR to `mate`, which works.

Looking at your `open_gem()` method it seems that the `system` call _should_ raise an exception, but somehow that doesn't get through… In fact, when I test it with `system("mate -w", ".")` it does return false, so this doesn't seem to be the problem. Maybe Ruby Gems silently ignores the raised exception?

**Comment by adamsanderson** [comment]
The newest version on Github will raise an error if <code>system</code> returns false.

Given that, I'd still like to know who to get system to handle $EDITOR with arguments.  I'll see what I can do.

**Comment by adamsanderson** [comment]
Should be fixed with gem 1.2

**Comment by grossbart** [comment]
It works perfectly now: arguments work and errors get raised, too. Thank you!
