### ISSUE TITLE
Publish gem to rubyforge?

### ISSUE THREAD

**Issue by thewoolleyman** [adamsanderson/open_gem#3]
This is a great gem.  Are you going to publish it on RubyForge's gem server?  So, like, non-cool-github-savvy normal people can find and download it?

**Comment by drnic** [comment]
+1

**Comment by adamsanderson** [comment]
Oh... yeah, that would be a good idea.
I'll hop on it right away.

**Comment by adamsanderson** [comment]
Ok, I submitted a request on rubyforge.  I'll close this when it's all up there.

**Comment by adamsanderson** [comment]
Done.  Go forth and 
    gem install open_gem
