### ISSUE TITLE
Use 'sudo' automatically to generate rdoc

### ISSUE THREAD

**Issue by drnic** [adamsanderson/open_gem#7]
I'll use `gem read xxx` to open rdoc; but if it doesn't exist and I say "y" then it fails because I'm not the root user.

Can the "read" command check for failed write attempts and then change to the root user automatically?

Nic

**Comment by adamsanderson** [comment]
Hmm... Should be possible, I'll look into it.  I think my system is set up to write it to the user's rdoc dir by default.  I'll see what I can do.

**Comment by daifu** [comment]
I use sudo gem read XXX, and I say "y", it said "Installing RDoc documentation for xxx". And I use gem read xxx again, but RDoc of xxx still did not exist.

I even try to reinstall the gem xxx with RDoc, but I still can not read the RDoc with gem read xxx.

Is that a bug or any solution?

**Comment by adamsanderson** [comment]
Does generating the rdoc fail?
Would you mind trying to run it as follows:
The rdoc seems to be missing, would you like to generate one? [Yn]  n

```
snappysalmon:liquid adam$ gem read activesupport -c echo
Open which gem?
 1. activesupport 2.1.2
 2. activesupport 2.3.8
 3. activesupport 3.0.0.beta4
 > 2
The rdoc seems to be missing, would you like to generate one? [Yn]  
Installing RDoc documentation for activesupport-2.3.8...
/Users/adam/.rvm/gems/ruby-1.9.1-p378/doc/activesupport-2.3.8/rdoc/index.html
```

Pick your gem, but try running it with `-c echo`.  Then take a look and see if the docs are actually generated in the location it prints out.

Also, which ruby distribution are you using?

**Comment by daifu** [comment]
Here is what i try for rails gem:
~: sudo gem read rails -c echo
Password:
Open which gem?
1. rails 1.2.6
2. rails 2.2.2
3. rails 2.3.5
4. rails 2.3.8
   > 4
   The rdoc seems to be missing, would you like to generate one? [Yn]  
   Installing RDoc documentation for rails-2.3.8...
   /Library/Ruby/Gems/1.8/doc/rails-2.3.8/rdoc/index.html
   ~: gem read rails -v=2.3.8
   The rdoc seems to be missing, would you like to generate one? [Yn]  
   ERROR:  While executing gem ... (Gem::FilePermissionError)
   You don't have write permissions into the /Library/Ruby/Gems/1.8/doc/rails-2.3.8 directory.

Try again:
~: gem read rails -v=2.3.8
The rdoc seems to be missing, would you like to generate one? [Yn]  
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /Library/Ruby/Gems/1.8/doc/rails-2.3.8 directory.
 ~: sudo gem read rails -v=2.3.8
The rdoc seems to be missing, would you like to generate one? [Yn]  
Installing RDoc documentation for rails-2.3.8...
 ~: sudo gem read rails -v=2.3.8
The rdoc seems to be missing, would you like to generate one? [Yn]  
Installing RDoc documentation for rails-2.3.8...

==comment
It did not read the rails gem's rdoc even though i already installed it, and ask me to install it again.

activesupport gem work for me, but I don't know why rails gem did not work.
I am using ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]
Thanks.

**Comment by adamsanderson** [comment]
That's odd, it goes through the same code path that ruby gems normally goes through to generate an rdoc.  I guess I can look into it some more.

**Comment by drnic** [comment]
Closing because it's really old
